// <auto-generated />
namespace GameNight.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _2nd3rdControllers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2nd3rdControllers));
        
        string IMigrationMetadata.Id
        {
            get { return "201904121459014_2nd3rdControllers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
